name: Check Commit
on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  SERVICE_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT }}

concurrency:
  group: check-commit-${{ github.event.repository.name }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-commit:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Secrets
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "key.json"
          encodedString: ${{ secrets.GCLOUD_SERVICE_KEY }}
      
      - name: Configure System and Project
        run: |
          gcloud auth configure-docker europe-west6-docker.pkg.dev
          export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/key.json
        
      - name: Unit Tests
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
          check-latest: true
          cache: true

      - run: make test
